-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  pseudo text,
  birth_year integer CHECK (birth_year >= 1900 AND birth_year::numeric <= EXTRACT(year FROM now())),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  bio text CHECK (length(bio) <= 500),
  city text CHECK (length(city) <= 100),
  state text CHECK (length(state) <= 100),
  name text CHECK (length(name) <= 100),
  profile_picture_url text,
  fitness_level text CHECK (fitness_level = ANY (ARRAY['newbie'::text, 'beginner'::text, 'intermediate'::text, 'advanced'::text])),
  unread_notifications_count integer DEFAULT 0,
  last_notification_read_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  latitude numeric CHECK (latitude IS NULL OR latitude >= '-90'::integer::numeric AND latitude <= 90::numeric),
  longitude numeric CHECK (longitude IS NULL OR longitude >= '-180'::integer::numeric AND longitude <= 180::numeric),
  opening_hours jsonb,
  is_open_24h boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  address text,
  contributor text CHECK (length(contributor) <= 100),
  rating integer CHECK (rating >= 1 AND rating <= 5),
  city text CHECK (length(city) <= 100),
  region text CHECK (length(region) <= 100),
  country text CHECK (length(country) <= 100),
  metadata jsonb,
  average_rating numeric DEFAULT NULL::numeric,
  rating_count integer DEFAULT 0,
  external_rating_count integer DEFAULT 0,
  external_average_rating numeric DEFAULT NULL::numeric,
  CONSTRAINT locations_pkey PRIMARY KEY (id),
  CONSTRAINT locations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.location_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location_id uuid,
  image_url text NOT NULL,
  image_path text NOT NULL,
  image_order integer NOT NULL CHECK (image_order >= 1 AND image_order <= 10),
  file_size integer CHECK (file_size > 0),
  mime_type text CHECK (mime_type = ANY (ARRAY['image/jpeg'::text, 'image/jpg'::text, 'image/png'::text, 'image/webp'::text, 'image/gif'::text, 'image/bmp'::text, 'image/tiff'::text])),
  created_at timestamp with time zone DEFAULT now(),
  uploaded_by uuid,
  CONSTRAINT location_images_pkey PRIMARY KEY (id),
  CONSTRAINT location_images_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT location_images_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.location_likes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location_id uuid,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT location_likes_pkey PRIMARY KEY (id),
  CONSTRAINT location_likes_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT location_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.location_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location_id uuid,
  user_id uuid,
  content text NOT NULL CHECK (length(content) > 0 AND length(content) <= 1000),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT location_comments_pkey PRIMARY KEY (id),
  CONSTRAINT location_comments_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT location_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.equipments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE CHECK (length(name) > 0 AND length(name) <= 100),
  category text NOT NULL CHECK (category = ANY (ARRAY['pull_up'::text, 'dips'::text, 'push_up'::text, 'core'::text, 'cardio'::text, 'flexibility'::text, 'balance'::text, 'strength'::text, 'plyometric'::text, 'other'::text])),
  description text CHECK (length(description) <= 500),
  icon_name text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  equipment_locale_key text NOT NULL UNIQUE,
  description_locale_key text,
  CONSTRAINT equipments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.location_equipments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location_id uuid NOT NULL,
  equipment_id uuid NOT NULL,
  quantity integer DEFAULT 1 CHECK (quantity > 0 AND quantity <= 50),
  condition text DEFAULT 'good'::text CHECK (condition = ANY (ARRAY['excellent'::text, 'good'::text, 'fair'::text, 'poor'::text])),
  notes text CHECK (length(notes) <= 200),
  added_by uuid,
  verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT location_equipments_pkey PRIMARY KEY (id),
  CONSTRAINT location_equipments_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT location_equipments_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipments(id),
  CONSTRAINT location_equipments_added_by_fkey FOREIGN KEY (added_by) REFERENCES public.users(id),
  CONSTRAINT location_equipments_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.disciplines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE CHECK (length(name) > 0 AND length(name) <= 100),
  category text NOT NULL CHECK (category = ANY (ARRAY['bodyweight'::text, 'strength'::text, 'cardio'::text, 'flexibility'::text, 'martial_arts'::text, 'gymnastics'::text, 'obstacle'::text, 'dance'::text, 'sport'::text, 'training'::text, 'other'::text])),
  description text CHECK (length(description) <= 500),
  icon_name text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  discipline_locale_key text NOT NULL UNIQUE,
  description_locale_key text,
  CONSTRAINT disciplines_pkey PRIMARY KEY (id)
);
CREATE TABLE public.location_disciplines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location_id uuid NOT NULL,
  discipline_id uuid NOT NULL,
  popularity_score integer DEFAULT 1 CHECK (popularity_score >= 1 AND popularity_score <= 5),
  notes text CHECK (length(notes) <= 200),
  added_by uuid,
  verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT location_disciplines_pkey PRIMARY KEY (id),
  CONSTRAINT location_disciplines_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT location_disciplines_discipline_id_fkey FOREIGN KEY (discipline_id) REFERENCES public.disciplines(id),
  CONSTRAINT location_disciplines_added_by_fkey FOREIGN KEY (added_by) REFERENCES public.users(id),
  CONSTRAINT location_disciplines_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.website_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT website_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_disciplines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  discipline_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_disciplines_pkey PRIMARY KEY (id),
  CONSTRAINT user_disciplines_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_disciplines_discipline_id_fkey FOREIGN KEY (discipline_id) REFERENCES public.disciplines(id)
);
CREATE TABLE public.clubs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL CHECK (length(TRIM(BOTH FROM name)) >= 1),
  description text CHECK (description IS NULL OR length(description) <= 500),
  privacy character varying NOT NULL CHECK (privacy::text = ANY (ARRAY['public'::character varying, 'private'::character varying]::text[])),
  category character varying NOT NULL,
  rules text CHECK (rules IS NULL OR length(rules) <= 1000),
  cover_image_url text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  search_vector tsvector DEFAULT to_tsvector('english'::regconfig, (((((name)::text || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || (category)::text)),
  CONSTRAINT clubs_pkey PRIMARY KEY (id),
  CONSTRAINT clubs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.club_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  club_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying NOT NULL DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['owner'::character varying, 'moderator'::character varying, 'member'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  joined_at timestamp with time zone DEFAULT now(),
  approved_at timestamp with time zone,
  approved_by uuid,
  CONSTRAINT club_members_pkey PRIMARY KEY (id),
  CONSTRAINT club_members_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.clubs(id),
  CONSTRAINT club_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT club_members_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.club_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  club_id uuid NOT NULL,
  author_id uuid NOT NULL,
  content text NOT NULL CHECK (length(content) >= 1 AND length(content) <= 2000),
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT club_posts_pkey PRIMARY KEY (id),
  CONSTRAINT club_posts_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.clubs(id),
  CONSTRAINT club_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.club_post_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  author_id uuid NOT NULL,
  content text NOT NULL CHECK (length(content) >= 1 AND length(content) <= 1000),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT club_post_comments_pkey PRIMARY KEY (id),
  CONSTRAINT club_post_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.club_posts(id),
  CONSTRAINT club_post_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.club_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  club_id uuid NOT NULL,
  tag character varying NOT NULL CHECK (length(TRIM(BOTH FROM tag)) >= 1),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT club_tags_pkey PRIMARY KEY (id),
  CONSTRAINT club_tags_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.clubs(id)
);
CREATE TABLE public.club_spots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  club_id uuid NOT NULL,
  location_id uuid NOT NULL,
  added_by uuid NOT NULL,
  added_at timestamp with time zone DEFAULT now(),
  CONSTRAINT club_spots_pkey PRIMARY KEY (id),
  CONSTRAINT club_spots_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.clubs(id),
  CONSTRAINT club_spots_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT club_spots_added_by_fkey FOREIGN KEY (added_by) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type IS NOT NULL AND type::text <> ''::text),
  title character varying NOT NULL,
  message text NOT NULL,
  club_id uuid,
  post_id uuid,
  comment_id uuid,
  actor_user_id uuid,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  event_participant_id uuid,
  app_version character varying,
  update_id character varying,
  metadata jsonb,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT notifications_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.clubs(id),
  CONSTRAINT notifications_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.club_posts(id),
  CONSTRAINT notifications_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.club_post_comments(id),
  CONSTRAINT notifications_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id),
  CONSTRAINT notifications_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT notifications_event_participant_id_fkey FOREIGN KEY (event_participant_id) REFERENCES public.event_participants(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  membership_requests boolean DEFAULT true,
  membership_updates boolean DEFAULT true,
  role_changes boolean DEFAULT true,
  new_posts boolean DEFAULT true,
  new_comments boolean DEFAULT true,
  post_likes boolean DEFAULT false,
  comment_likes boolean DEFAULT false,
  push_notifications boolean DEFAULT true,
  email_notifications boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  push_membership_requests boolean DEFAULT true,
  push_membership_updates boolean DEFAULT true,
  push_role_changes boolean DEFAULT true,
  push_new_posts boolean DEFAULT false,
  push_new_comments boolean DEFAULT true,
  push_post_likes boolean DEFAULT false,
  push_comment_likes boolean DEFAULT false,
  push_mentions boolean DEFAULT true,
  event_created boolean DEFAULT true,
  event_updates boolean DEFAULT true,
  event_participants boolean DEFAULT true,
  event_approvals boolean DEFAULT true,
  event_reminders boolean DEFAULT true,
  push_event_created boolean DEFAULT true,
  push_event_updates boolean DEFAULT true,
  push_event_participants boolean DEFAULT true,
  push_event_approvals boolean DEFAULT true,
  push_event_reminders boolean DEFAULT true,
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.club_post_likes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT club_post_likes_pkey PRIMARY KEY (id),
  CONSTRAINT club_post_likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.club_posts(id),
  CONSTRAINT club_post_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_push_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  expo_push_token text NOT NULL,
  device_info jsonb DEFAULT '{}'::jsonb,
  last_used_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_push_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT user_push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.push_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notification_id uuid NOT NULL,
  user_id uuid NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying, 'expired'::character varying]::text[])),
  attempts integer DEFAULT 0,
  sent_at timestamp with time zone,
  error_details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT push_queue_pkey PRIMARY KEY (id),
  CONSTRAINT push_queue_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id),
  CONSTRAINT push_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.event_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  name_fr text NOT NULL,
  color text NOT NULL DEFAULT '#3B82F6'::text,
  icon text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_tags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL CHECK (length(title) >= 3 AND length(title) <= 100),
  description text CHECK (length(description) <= 2000),
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  timezone text NOT NULL DEFAULT 'UTC'::text,
  max_participants integer CHECK (max_participants > 0),
  min_participants integer DEFAULT 1 CHECK (min_participants > 0),
  registration_deadline timestamp with time zone,
  is_free boolean NOT NULL DEFAULT true,
  price_amount numeric CHECK (price_amount >= 0::numeric),
  price_currency text DEFAULT 'EUR'::text,
  visibility text NOT NULL DEFAULT 'public'::text CHECK (visibility = ANY (ARRAY['public'::text, 'private'::text, 'club_only'::text])),
  requires_approval boolean NOT NULL DEFAULT false,
  club_id uuid,
  created_by uuid NOT NULL,
  organizer_name text,
  organizer_contact text,
  status text NOT NULL DEFAULT 'upcoming'::text CHECK (status = ANY (ARRAY['draft'::text, 'upcoming'::text, 'ongoing'::text, 'completed'::text, 'cancelled'::text])),
  cancellation_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  featured_image_url text,
  featured_image_path text,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.clubs(id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.event_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  location_id uuid NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  location_order integer NOT NULL DEFAULT 1,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_locations_pkey PRIMARY KEY (id),
  CONSTRAINT event_locations_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_locations_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.event_tag_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_tag_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT event_tag_assignments_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_tag_assignments_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.event_tags(id)
);
CREATE TABLE public.event_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  user_id uuid NOT NULL,
  participation_type text NOT NULL CHECK (participation_type = ANY (ARRAY['interested'::text, 'participating'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'waitlisted'::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  payment_status text DEFAULT 'not_required'::text CHECK (payment_status = ANY (ARRAY['not_required'::text, 'pending'::text, 'completed'::text, 'refunded'::text])),
  payment_reference text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_participants_pkey PRIMARY KEY (id),
  CONSTRAINT event_participants_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT event_participants_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.event_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  image_url text NOT NULL,
  image_path text NOT NULL,
  image_order integer NOT NULL CHECK (image_order >= 1 AND image_order <= 10),
  caption text CHECK (length(caption) <= 200),
  file_size integer CHECK (file_size > 0),
  mime_type text CHECK (mime_type = ANY (ARRAY['image/jpeg'::text, 'image/png'::text, 'image/webp'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_images_pkey PRIMARY KEY (id),
  CONSTRAINT event_images_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.event_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  author_id uuid NOT NULL,
  content text NOT NULL CHECK (length(content) >= 1 AND length(content) <= 2000),
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_posts_pkey PRIMARY KEY (id),
  CONSTRAINT event_posts_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.event_post_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  author_id uuid NOT NULL,
  content text NOT NULL CHECK (length(content) >= 1 AND length(content) <= 1000),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_post_comments_pkey PRIMARY KEY (id),
  CONSTRAINT event_post_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.event_posts(id),
  CONSTRAINT event_post_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.event_post_likes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_post_likes_pkey PRIMARY KEY (id),
  CONSTRAINT event_post_likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.event_posts(id),
  CONSTRAINT event_post_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.location_ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location_id uuid NOT NULL,
  user_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT location_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT location_ratings_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT location_ratings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.muscles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  name_locale_key character varying NOT NULL,
  muscle_group character varying NOT NULL,
  description text,
  anatomy_image_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT muscles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  revenuecat_customer_id character varying UNIQUE,
  product_id character varying NOT NULL,
  subscription_tier character varying CHECK (subscription_tier::text = ANY (ARRAY['free'::character varying, 'premium'::character varying, 'pro'::character varying]::text[])),
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['active'::character varying, 'cancelled'::character varying, 'expired'::character varying, 'trial'::character varying, 'grace_period'::character varying]::text[])),
  started_at timestamp with time zone NOT NULL,
  current_period_start timestamp with time zone NOT NULL,
  current_period_end timestamp with time zone NOT NULL,
  cancelled_at timestamp with time zone,
  expires_at timestamp with time zone,
  trial_start timestamp with time zone,
  trial_end timestamp with time zone,
  is_trial_used boolean DEFAULT false,
  platform character varying CHECK (platform::text = ANY (ARRAY['ios'::character varying, 'android'::character varying, 'web'::character varying]::text[])),
  store_transaction_id character varying,
  ai_generations_used integer DEFAULT 0,
  ai_generations_limit integer,
  ai_generation_reset_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_workout_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  fitness_level character varying CHECK (fitness_level::text = ANY (ARRAY['beginner'::character varying, 'intermediate'::character varying, 'advanced'::character varying, 'expert'::character varying]::text[])),
  fitness_goals ARRAY,
  preferred_workout_duration integer,
  preferred_difficulty integer CHECK (preferred_difficulty >= 1 AND preferred_difficulty <= 5),
  preferred_workout_types ARRAY,
  preferred_equipment ARRAY,
  excluded_exercises ARRAY,
  excluded_muscle_groups ARRAY,
  injuries ARRAY,
  medical_conditions ARRAY,
  mobility_restrictions jsonb,
  workouts_per_week integer,
  preferred_workout_days ARRAY,
  preferred_workout_times ARRAY,
  variety_preference integer CHECK (variety_preference >= 1 AND variety_preference <= 5),
  instruction_detail_level character varying CHECK (instruction_detail_level::text = ANY (ARRAY['minimal'::character varying, 'standard'::character varying, 'detailed'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_workout_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_workout_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.workout_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  workout_id uuid NOT NULL,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  duration_seconds integer,
  calories_burned integer,
  average_heart_rate integer,
  max_heart_rate integer,
  status character varying NOT NULL DEFAULT 'in_progress'::character varying CHECK (status::text = ANY (ARRAY['in_progress'::character varying, 'completed'::character varying, 'paused'::character varying, 'abandoned'::character varying]::text[])),
  completion_percentage numeric,
  difficulty_rating integer CHECK (difficulty_rating >= 1 AND difficulty_rating <= 5),
  enjoyment_rating integer CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  notes text,
  location_id uuid,
  performed_at_coordinates USER-DEFINED,
  device_info jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT workout_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT workout_sessions_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT workout_sessions_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workouts(id)
);
CREATE TABLE public.session_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  workout_exercise_id uuid NOT NULL,
  sets_completed integer,
  reps_completed ARRAY,
  weight_used_kg ARRAY,
  duration_seconds integer,
  distance_meters numeric,
  max_heart_rate integer,
  calories_burned integer,
  completed boolean DEFAULT false,
  skipped boolean DEFAULT false,
  modified boolean DEFAULT false,
  modification_notes text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT session_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT session_exercises_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.workout_sessions(id),
  CONSTRAINT session_exercises_set_exercise_id_fkey FOREIGN KEY (workout_exercise_id) REFERENCES public.set_exercises(id)
);
CREATE TABLE public.workout_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workout_id uuid NOT NULL,
  shared_by uuid NOT NULL,
  club_id uuid,
  location_id uuid,
  share_type character varying CHECK (share_type::text = ANY (ARRAY['club'::character varying, 'location'::character varying, 'public'::character varying]::text[])),
  message text,
  allow_copy boolean DEFAULT true,
  allow_modify boolean DEFAULT false,
  shared_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT workout_shares_pkey PRIMARY KEY (id),
  CONSTRAINT workout_shares_shared_by_fkey FOREIGN KEY (shared_by) REFERENCES auth.users(id),
  CONSTRAINT workout_shares_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.clubs(id),
  CONSTRAINT workout_shares_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.workout_likes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workout_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_likes_pkey PRIMARY KEY (id),
  CONSTRAINT workout_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.workout_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  category character varying NOT NULL,
  author_id uuid,
  is_official boolean DEFAULT false,
  is_premium boolean DEFAULT false,
  base_workout_data jsonb NOT NULL,
  customization_options jsonb,
  times_used integer DEFAULT 0,
  average_rating numeric,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_templates_pkey PRIMARY KEY (id),
  CONSTRAINT workout_templates_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id)
);
CREATE TABLE public.workout_template_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  exercise_id uuid,
  order_index integer NOT NULL,
  sets integer,
  reps integer,
  duration_seconds integer,
  rest_seconds integer,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_template_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT workout_template_exercises_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.workout_templates(id),
  CONSTRAINT workout_template_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  name_locale_key character varying NOT NULL,
  aliases ARRAY,
  description text,
  description_locale_key character varying,
  category USER-DEFINED NOT NULL,
  subcategory character varying NOT NULL,
  exercise_family character varying NOT NULL,
  difficulty_level integer CHECK (difficulty_level >= 1 AND difficulty_level <= 10),
  progression_tier integer,
  prerequisites ARRAY,
  movement_pattern USER-DEFINED NOT NULL,
  primary_muscles ARRAY,
  secondary_muscles ARRAY,
  joint_actions ARRAY,
  plane_of_motion ARRAY,
  force_vector USER-DEFINED NOT NULL DEFAULT 'diagonal'::force_vector,
  parameter_type USER-DEFINED NOT NULL DEFAULT 'reps'::parameter_type,
  supports_reps boolean DEFAULT true,
  supports_time boolean DEFAULT false,
  supports_distance boolean DEFAULT false,
  beginner_sets ARRAY DEFAULT '{2,3}'::integer[],
  intermediate_sets ARRAY DEFAULT '{3,4}'::integer[],
  advanced_sets ARRAY DEFAULT '{3,5}'::integer[],
  beginner_reps ARRAY DEFAULT '{5,12}'::integer[],
  intermediate_reps ARRAY DEFAULT '{8,15}'::integer[],
  advanced_reps ARRAY DEFAULT '{10,20}'::integer[],
  beginner_time ARRAY DEFAULT '{15,45}'::integer[],
  intermediate_time ARRAY DEFAULT '{30,90}'::integer[],
  advanced_time ARRAY DEFAULT '{45,120}'::integer[],
  space_requirement USER-DEFINED DEFAULT 'minimal'::space_requirement,
  surface_types ARRAY DEFAULT '{concrete,grass}'::surface_type[],
  safety_level USER-DEFINED DEFAULT 'moderate'::safety_level,
  injury_risks ARRAY,
  contraindications ARRAY,
  coaching_cues ARRAY,
  common_mistakes ARRAY,
  setup_instructions text,
  execution_instructions text,
  breathing_pattern text,
  image_url text,
  video_url text,
  animation_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_verified boolean DEFAULT false,
  popularity_score numeric DEFAULT 0.0,
  is_active boolean DEFAULT true,
  CONSTRAINT exercises_pkey PRIMARY KEY (id)
);
CREATE TABLE public.exercise_progressions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exercise_id uuid NOT NULL,
  progression_type USER-DEFINED NOT NULL,
  target_exercise_id uuid NOT NULL,
  difficulty_gap integer NOT NULL CHECK (difficulty_gap >= 1 AND difficulty_gap <= 5),
  transition_requirements text,
  mastery_criteria text,
  estimated_transition_time integer,
  confidence_score numeric DEFAULT 1.0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exercise_progressions_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_progressions_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT exercise_progressions_target_exercise_id_fkey FOREIGN KEY (target_exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.exercise_equipment (
  exercise_id uuid NOT NULL,
  equipment_id uuid NOT NULL,
  requirement_type USER-DEFINED NOT NULL,
  quantity integer DEFAULT 1,
  usage_notes text,
  CONSTRAINT exercise_equipment_pkey PRIMARY KEY (exercise_id, equipment_id),
  CONSTRAINT exercise_equipment_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT exercise_equipment_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipments(id)
);
CREATE TABLE public.exercise_muscles (
  exercise_id uuid NOT NULL,
  muscle_id uuid NOT NULL,
  involvement_type USER-DEFINED NOT NULL,
  activation_percentage integer CHECK (activation_percentage >= 1 AND activation_percentage <= 100),
  CONSTRAINT exercise_muscles_pkey PRIMARY KEY (exercise_id, muscle_id),
  CONSTRAINT exercise_muscles_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT exercise_muscles_muscle_id_fkey FOREIGN KEY (muscle_id) REFERENCES public.muscles(id)
);
CREATE TABLE public.sets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying,
  description text,
  type USER-DEFINED NOT NULL,
  rounds integer NOT NULL DEFAULT 1,
  rest_between_exercises integer,
  rest_between_rounds integer,
  rest_after_set integer,
  time_domain integer,
  target_rounds integer,
  score_method USER-DEFINED,
  instructions text,
  coaching_notes ARRAY,
  difficulty_level integer CHECK (difficulty_level >= 1 AND difficulty_level <= 10),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  is_template boolean DEFAULT false,
  CONSTRAINT sets_pkey PRIMARY KEY (id),
  CONSTRAINT sets_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.set_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  set_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  order_in_set integer NOT NULL,
  parameter_type USER-DEFINED NOT NULL,
  target_value integer,
  target_range_min integer,
  target_range_max integer,
  intensity_percentage integer CHECK (intensity_percentage >= 1 AND intensity_percentage <= 100),
  tempo character varying,
  range_of_motion USER-DEFINED DEFAULT 'full'::rom_specification,
  rest_before integer,
  time_cap integer,
  cluster_rest integer,
  isometric_holds jsonb,
  modifications jsonb,
  coaching_cues ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT set_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT set_exercises_set_id_fkey FOREIGN KEY (set_id) REFERENCES public.sets(id),
  CONSTRAINT set_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.workouts_backup (
  id uuid,
  user_id uuid,
  location_id uuid,
  club_id uuid,
  name character varying,
  description text,
  type character varying,
  difficulty_level integer,
  estimated_duration integer,
  estimated_calories integer,
  is_ai_generated boolean,
  ai_provider character varying,
  ai_model character varying,
  generation_params jsonb,
  prompt_tokens integer,
  completion_tokens integer,
  is_public boolean,
  is_template boolean,
  share_token character varying,
  times_completed integer,
  average_rating numeric,
  likes_count integer,
  tags ARRAY,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone
);
CREATE TABLE public.workouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name character varying NOT NULL,
  description text,
  type USER-DEFINED NOT NULL,
  focus_areas ARRAY,
  training_style USER-DEFINED,
  difficulty_level integer CHECK (difficulty_level >= 1 AND difficulty_level <= 10),
  estimated_duration integer,
  equipment_needed ARRAY,
  space_requirements USER-DEFINED DEFAULT 'minimal'::space_requirement,
  energy_system ARRAY,
  primary_adaptations ARRAY,
  is_ai_generated boolean DEFAULT false,
  ai_provider character varying,
  ai_model character varying,
  ai_generation_params jsonb,
  ai_prompt_tokens integer,
  ai_completion_tokens integer,
  is_public boolean DEFAULT false,
  is_template boolean DEFAULT false,
  share_token character varying UNIQUE,
  times_completed integer DEFAULT 0,
  average_rating numeric,
  likes_count integer DEFAULT 0,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT workouts_pkey PRIMARY KEY (id),
  CONSTRAINT workouts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.workout_sets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workout_id uuid NOT NULL,
  set_id uuid NOT NULL,
  phase USER-DEFINED NOT NULL,
  order_in_phase integer NOT NULL,
  phase_modifications jsonb,
  transition_notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_sets_pkey PRIMARY KEY (id),
  CONSTRAINT workout_sets_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workouts(id),
  CONSTRAINT workout_sets_set_id_fkey FOREIGN KEY (set_id) REFERENCES public.sets(id)
);
CREATE TABLE public.programs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  summary text,
  duration_weeks integer NOT NULL CHECK (duration_weeks >= 1 AND duration_weeks <= 52),
  sessions_per_week integer NOT NULL CHECK (sessions_per_week >= 1 AND sessions_per_week <= 14),
  estimated_session_duration integer,
  program_type text NOT NULL DEFAULT 'strength'::text,
  difficulty_level integer NOT NULL DEFAULT 5 CHECK (difficulty_level >= 1 AND difficulty_level <= 10),
  target_population ARRAY,
  periodization_model USER-DEFINED NOT NULL DEFAULT 'linear'::periodization_model,
  periodization_config jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  is_public boolean NOT NULL DEFAULT false,
  is_template boolean NOT NULL DEFAULT false,
  template_category text,
  primary_goals ARRAY NOT NULL DEFAULT '{}'::text[],
  secondary_goals ARRAY DEFAULT '{}'::text[],
  equipment_requirements ARRAY DEFAULT '{}'::uuid[],
  space_requirements ARRAY,
  prerequisites jsonb DEFAULT '{}'::jsonb,
  contraindications jsonb DEFAULT '{}'::jsonb,
  special_considerations text,
  is_ai_generated boolean NOT NULL DEFAULT false,
  ai_provider text,
  ai_model text,
  generation_params jsonb,
  generation_prompt text,
  tags ARRAY DEFAULT '{}'::text[],
  version integer NOT NULL DEFAULT 1,
  license text,
  attribution text,
  total_enrollments integer NOT NULL DEFAULT 0,
  completion_rate numeric,
  average_rating numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  published_at timestamp with time zone,
  archived_at timestamp with time zone,
  CONSTRAINT programs_pkey PRIMARY KEY (id),
  CONSTRAINT programs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.program_phases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  phase_type USER-DEFINED NOT NULL DEFAULT 'build'::program_phase,
  order_index integer NOT NULL,
  duration_weeks integer NOT NULL CHECK (duration_weeks >= 1),
  start_week integer NOT NULL CHECK (start_week >= 1),
  intensity_range ARRAY DEFAULT '{5,7}'::integer[],
  volume_emphasis text DEFAULT 'moderate'::text,
  focus_areas ARRAY DEFAULT '{}'::text[],
  training_emphasis jsonb DEFAULT '{}'::jsonb,
  recovery_emphasis jsonb DEFAULT '{}'::jsonb,
  deload_protocol jsonb DEFAULT '{}'::jsonb,
  assessments jsonb DEFAULT '{}'::jsonb,
  milestones jsonb DEFAULT '{}'::jsonb,
  progression_rules jsonb DEFAULT '{}'::jsonb,
  adaptation_triggers jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT program_phases_pkey PRIMARY KEY (id),
  CONSTRAINT program_phases_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id)
);
CREATE TABLE public.program_weeks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  phase_id uuid,
  week_number integer NOT NULL CHECK (week_number >= 1),
  name text,
  description text,
  intensity_target integer CHECK (intensity_target >= 1 AND intensity_target <= 10),
  volume_target text,
  is_deload_week boolean NOT NULL DEFAULT false,
  is_test_week boolean NOT NULL DEFAULT false,
  planned_sessions integer NOT NULL CHECK (planned_sessions >= 1),
  rest_days integer DEFAULT 1,
  coaching_notes text,
  user_instructions text,
  preparation_notes text,
  alternative_options jsonb DEFAULT '{}'::jsonb,
  scaling_options jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT program_weeks_pkey PRIMARY KEY (id),
  CONSTRAINT program_weeks_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT program_weeks_phase_id_fkey FOREIGN KEY (phase_id) REFERENCES public.program_phases(id)
);
CREATE TABLE public.program_workouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  week_id uuid NOT NULL,
  workout_id uuid,
  day_of_week integer NOT NULL CHECK (day_of_week >= 1 AND day_of_week <= 7),
  session_order integer NOT NULL DEFAULT 1,
  session_type text NOT NULL DEFAULT 'main'::text,
  session_priority text NOT NULL DEFAULT 'required'::text,
  workout_modifications jsonb DEFAULT '{}'::jsonb,
  scaling_instructions text,
  substitution_options jsonb DEFAULT '{}'::jsonb,
  pre_session_notes text,
  post_session_notes text,
  recovery_protocols text,
  estimated_duration integer,
  difficulty_override integer CHECK (difficulty_override >= 1 AND difficulty_override <= 10),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT program_workouts_pkey PRIMARY KEY (id),
  CONSTRAINT program_workouts_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT program_workouts_week_id_fkey FOREIGN KEY (week_id) REFERENCES public.program_weeks(id),
  CONSTRAINT program_workouts_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workouts(id)
);
CREATE TABLE public.user_program_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  program_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'active'::program_status,
  enrollment_date timestamp with time zone NOT NULL DEFAULT now(),
  start_date timestamp with time zone NOT NULL DEFAULT now(),
  target_completion_date timestamp with time zone,
  actual_completion_date timestamp with time zone,
  current_week integer NOT NULL DEFAULT 1,
  current_phase_id uuid,
  weeks_completed integer NOT NULL DEFAULT 0,
  sessions_completed integer NOT NULL DEFAULT 0,
  sessions_skipped integer NOT NULL DEFAULT 0,
  adherence_rate numeric,
  progression_rate numeric,
  satisfaction_rating integer CHECK (satisfaction_rating >= 1 AND satisfaction_rating <= 5),
  personal_modifications jsonb DEFAULT '{}'::jsonb,
  coach_notes text,
  user_goals jsonb DEFAULT '{}'::jsonb,
  total_paused_days integer DEFAULT 0,
  last_paused_at timestamp with time zone,
  pause_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_program_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT user_program_enrollments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_program_enrollments_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT user_program_enrollments_current_phase_id_fkey FOREIGN KEY (current_phase_id) REFERENCES public.program_phases(id)
);
CREATE TABLE public.program_session_completions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enrollment_id uuid NOT NULL,
  program_workout_id uuid NOT NULL,
  workout_session_id uuid,
  status text NOT NULL DEFAULT 'completed'::text,
  completion_date timestamp with time zone NOT NULL DEFAULT now(),
  scheduled_date date,
  actual_duration integer,
  perceived_exertion integer CHECK (perceived_exertion >= 1 AND perceived_exertion <= 10),
  session_rating integer CHECK (session_rating >= 1 AND session_rating <= 5),
  modifications_made jsonb DEFAULT '{}'::jsonb,
  equipment_substitutions jsonb DEFAULT '{}'::jsonb,
  exercise_substitutions jsonb DEFAULT '{}'::jsonb,
  user_notes text,
  difficulty_feedback text,
  energy_level text,
  motivation_level text,
  pre_session_readiness integer CHECK (pre_session_readiness >= 1 AND pre_session_readiness <= 10),
  post_session_fatigue integer CHECK (post_session_fatigue >= 1 AND post_session_fatigue <= 10),
  recovery_rating integer CHECK (recovery_rating >= 1 AND recovery_rating <= 10),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT program_session_completions_pkey PRIMARY KEY (id),
  CONSTRAINT program_session_completions_workout_session_id_fkey FOREIGN KEY (workout_session_id) REFERENCES public.workout_sessions(id),
  CONSTRAINT program_session_completions_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.user_program_enrollments(id),
  CONSTRAINT program_session_completions_program_workout_id_fkey FOREIGN KEY (program_workout_id) REFERENCES public.program_workouts(id)
);
CREATE TABLE public.program_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  user_id uuid NOT NULL,
  enrollment_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  review_text text,
  effectiveness_rating integer CHECK (effectiveness_rating >= 1 AND effectiveness_rating <= 5),
  difficulty_rating integer CHECK (difficulty_rating >= 1 AND difficulty_rating <= 5),
  enjoyment_rating integer CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  weeks_completed integer,
  user_fitness_level text,
  user_goals ARRAY,
  would_recommend boolean,
  recommended_for ARRAY,
  not_recommended_for ARRAY,
  is_verified boolean NOT NULL DEFAULT false,
  is_featured boolean NOT NULL DEFAULT false,
  is_hidden boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT program_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT program_reviews_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT program_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT program_reviews_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.user_program_enrollments(id)
);
